# AUTO-GENERATED by .shared/codegen/python_gen.py - do not edit by hand
#
# These models enforce SHAPE only. Most constraints declared in the JSON
# schemas (numeric ranges, enums, minLength, etc.) are NOT enforced by
# these classes. ConfigDict(extra='forbid') is applied where the schema
# has additionalProperties:false, and `const` properties become Literal[],
# so the most common boundary divergences are caught. For full validation
# call jsonschema.validate() against the schema in C:/Dev/.shared/schemas/.
from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict

# from action.schema.json
class ActionRequest(BaseModel):
    schema_version: Literal['1.0.0'] = '1.0.0'
    session_id: str
    actor_id: str
    target_id: str | None = None
    player_input: str
    actor_stats: dict[str, Any]
    target_stats: dict | None = None
    scene_context: dict[str, Any] | None = None
    recent_history: list[str] | None = None
    request_type: str | None = None
    party: list[dict[str, Any]] | None = None

# from decision.schema.json
class DecisionPayload(BaseModel):
    schema_version: Literal['1.0.0'] = '1.0.0'
    session_id: str
    success: bool
    scale: int
    narrative_text: str
    stat_effects: list[dict[str, Any]] | None = None
    fx_requests: list[dict[str, Any]] | None = None
    repetition_penalty: int | None = None
    deterministic_fallback: bool | None = False
    encounter_template: dict | None = None
    atmospherics: dict | None = None

# from selection.schema.json
class AssetSelectionRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: Literal['1.0.0'] = '1.0.0'
    kind: str
    biome: str | None = None
    theme: str | None = None
    tags: list[str] | None = None
    constraints: dict[str, Any] | None = None
    allow_ai_generation: bool | None = False
