# AUTO-GENERATED by .shared/codegen/python_gen.py - do not edit by hand
#
# These models enforce SHAPE only. Most constraints declared in the JSON
# schemas (numeric ranges, enums, minLength, etc.) are NOT enforced by
# these classes. ConfigDict(extra='forbid') is applied where the schema
# has additionalProperties:false, and `const` properties become Literal[],
# so the most common boundary divergences are caught. For full validation
# call jsonschema.validate() against the schema in C:/Dev/.shared/schemas/.
from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict

# from action.schema.json
class ActionRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: Literal['1.0.0'] = '1.0.0'
    session_id: str
    actor_id: str
    target_id: Optional[str] = None
    player_input: str
    actor_stats: dict[str, Any]
    target_stats: Optional[dict] = None
    scene_context: Optional[dict[str, Any]] = None
    recent_history: Optional[list[str]] = None

# from decision.schema.json
class DecisionPayload(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: Literal['1.0.0'] = '1.0.0'
    session_id: str
    success: bool
    scale: int
    narrative_text: str
    stat_effects: Optional[list[dict[str, Any]]] = None
    fx_requests: Optional[list[dict[str, Any]]] = None
    repetition_penalty: Optional[int] = None
    deterministic_fallback: Optional[bool] = False

# from selection.schema.json
class AssetSelectionRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: Literal['1.0.0'] = '1.0.0'
    kind: str
    biome: Optional[str] = None
    theme: Optional[str] = None
    tags: Optional[list[str]] = None
    constraints: Optional[dict[str, Any]] = None
    allow_ai_generation: Optional[bool] = False
